id: jie_ball
name: jie
name[zh]: 钢珠位置
version: 1.0.0
icon: app.png
author: liuargo
desc: demo
desc[zh]: 检测并显示钢珠在摆杆上的标定位置。
files:
  - models\yolo26_all_maixcam_yolo26_480_160\yolo26_all_tensor_info.txt
  - models\yolo26_all_maixcam_yolo26_480_160\yolo26_all.cvimodel
  - models\yolo26_all_maixcam_yolo26_480_160\yolo26_all.mud
  - ball_position.py
  - main.py
